### ISSUE TITLE
Received an errors after compiling

### ISSUE THREAD

**Issue by franksvision** [strasdat/VisionTools#1]
After following the ScaViSLAM instructions, I received the following errors. 
I back tracked my steps several times but I can't find any mistakes. 

Thanks,

Frank

Linking CXX shared library libVisionTools.so
/usr/bin/cmake -E cmake_link_script CMakeFiles/VisionTools.dir/link.txt --verbose=1
/usr/bin/c++  -fPIC -O3 -g   -shared -Wl,-soname,libVisionTools.so -o libVisionTools.so CMakeFiles/VisionTools.dir/visiontools/draw2d.cpp.o CMakeFiles/VisionTools.dir/visiontools/draw3d.cpp.o CMakeFiles/VisionTools.dir/visiontools/sample.cpp.o CMakeFiles/VisionTools.dir/visiontools/performance_monitor.cpp.o CMakeFiles/VisionTools.dir/visiontools/linear_camera.cpp.o -lGL /home/franksvision/MY_SOFTWARE_DIRECTORY/ScaViSLAM/EXTERNAL/Pangolin/svs_build/pangolin/libpangolin.a -lglut /home/franksvision/MY_SOFTWARE_DIRECTORY/ScaViSLAM/EXTERNAL/opencv2/svs_build/lib/libopencv_core.so /home/franksvision/MY_SOFTWARE_DIRECTORY/ScaViSLAM/EXTERNAL/opencv2/svs_build/lib/libopencv_features2d.so /home/franksvision/MY_SOFTWARE_DIRECTORY/ScaViSLAM/EXTERNAL/opencv2/svs_build/lib/libopencv_flann.so /home/franksvision/MY_SOFTWARE_DIRECTORY/ScaViSLAM/EXTERNAL/opencv2/svs_build/lib/libopencv_gpu.so /home/franksvision/MY_SOFTWARE_DIRECTORY/ScaViSLAM/EXTERNAL/opencv2/svs_build/lib/libopencv_highgui.so /home/franksvision/MY_SOFTWARE_DIRECTORY/ScaViSLAM/EXTERNAL/opencv2/svs_build/lib/libopencv_imgproc.so /home/franksvision/MY_SOFTWARE_DIRECTORY/ScaViSLAM/EXTERNAL/opencv2/svs_build/lib/libopencv_calib3d.so -Wl,-rpath,/home/franksvision/MY_SOFTWARE_DIRECTORY/ScaViSLAM/EXTERNAL/opencv2/svs_build/lib 
/usr/bin/ld: /home/franksvision/MY_SOFTWARE_DIRECTORY/ScaViSLAM/EXTERNAL/Pangolin/svs_build/pangolin/libpangolin.a(display.cpp.o): relocation R_X86_64_TPOFF32 against `pangolin::context' can not be used when making a shared object; recompile with -fPIC
/home/franksvision/MY_SOFTWARE_DIRECTORY/ScaViSLAM/EXTERNAL/Pangolin/svs_build/pangolin/libpangolin.a: could not read symbols: Bad value
collect2: ld returned 1 exit status
make[2]: *** [libVisionTools.so] Error 1
make[2]: Leaving directory`/home/franksvision/MY_SOFTWARE_DIRECTORY/ScaViSLAM/EXTERNAL/VisionTools/svs_build'
make[1]: **\* [CMakeFiles/VisionTools.dir/all] Error 2
make[1]: Leaving directory `/home/franksvision/MY_SOFTWARE_DIRECTORY/ScaViSLAM/EXTERNAL/VisionTools/svs_build'
make: **\* [all] Error 2

**Comment by strasdat** [comment]
There is something wrong with the interaction between Pangolin and VisionTools. I could reproduce your error.

Could you please check out an older version of Pangolin (git checkout cad267, I had to comment out "VBODisplay" in "example/CMakeLists.txt" in this version),
and I'll look into this issue in the meantime.

**Comment by strasdat** [comment]
I found the problem. In the newest version of Pangolin, a static library is built by default. If you change Pangolin's CMakefile to build a shared library, everything should work smoothly. I'll update the README accordingly later today.

**Comment by franksvision** [comment]
Sorry for the delay.. That worked!
Thanks for the update.
